### ISSUE TITLE
Ubuntu 14.04  tlsv1 error

### ISSUE THREAD

**Issue by noenthu** [humla/canadanepal-xbmc#27]
Using 1.3.8 version of the addon on an ubuntu 14.04 system with python 2.7.6
On testing this is the error

```
3:08:22.733 T:140074687641344  NOTICE: https://einthusan.tv/movie/results/?lang=telugu&find=Year&year=2017
13:08:22.809 T:140074687641344   ERROR: /home/vivek/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              SNIMissingWarning
13:08:22.809 T:140074687641344   ERROR: /home/vivek/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
13:08:22.853 T:140074687641344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
                                            Traceback (most recent call last):
                                              File "/home/vivek/.kodi/addons/plugin.video.einthusan/default.py", line 601, in <module>
                                                function_map[mode](name, url, language, mode)
                                              File "/home/vivek/.kodi/addons/plugin.video.einthusan/default.py", line 86, in get_movies_and_music_videos
                                                get_movies_and_music_videos_helper(name, url, language, mode, 1)
                                              File "/home/vivek/.kodi/addons/plugin.video.einthusan/default.py", line 92, in get_movies_and_music_videos_helper
                                                html =  requests.get(url).text
                                              File "/home/vivek/.kodi/addons/script.module.requests/lib/requests/api.py", line 70, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/vivek/.kodi/addons/script.module.requests/lib/requests/api.py", line 56, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/vivek/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/vivek/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/vivek/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 497, in send
                                                raise SSLError(e, request=request)
                                            SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
                                            -->End of Python script error report<--
```

**Comment by Gujal00** [comment]
Python 2.7.6 will not work as it lacks TLS1.2 support which is essential for einthusan website. I think the minimum version required is 2.7,9 (or may be 10)
With Ubuntu 14.04LTS you are stuck at Python 2.7.6. can't do anything about it.

**Comment by noenthu** [comment]
Was able to get it to work following these steps
http://kodi.wiki/view/HOW-TO:Upgrade_Python_interpreter_on_Linux

Initial attempt to install an alternate python 2.7.13 in /usr/local/ did not work.

**Comment by Gujal00** [comment]
Fantastic, can you close the issue.
